Repository maboroshi-inc/type-assertions, pull requests merged in 2019-12, with the labels that each got.

#27 `isBigInt()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#21 `isArray()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#19 `isNaN()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#20 `isStrictNumber()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#42 `isInteger()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#37 `isError()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#41 `isFiniteNumber()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#36 feat: implement isMap
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#44 `isNull()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#46 feat: implement isWeakMap
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#48 feat: implement isSet
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#52 `isRegExp()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#47 `isObject()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#53 feat: implement isWeakSet
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#54 feat: implement isValidDate #13
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#56 `isSafeInteger()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#57 `isString()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#58 `isSymbol()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#59 `isUndefined()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#61 `isPlainObject()` を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#60 feat: implement isFunction #13
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#68 feat: implement isGeneratorFunction #13
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: enhancement

#13 公開する機能を実装する
  __tests__/asserts.spec.ts
  __tests__/checks.spec.ts
  __tests__/index.spec.ts
  src/asserts.ts
  src/checks.ts
Labels: help wanted

#73 prepare for v1.0.0
  README.md
  package-lock.json
  package.json
  src/asserts.ts
  src/guards.ts
Labels: documentation
